In [4]:
import numpy as np 

In [6]:
arr = np.arange(60).reshape(15,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [8]:
arr[5,2]

22

In [10]:
arr[5,2]=300
arr[5,2]

300

In [11]:
arr[0]

array([0, 1, 2, 3])

In [12]:
arr[0]=[34, 45, 56, 78]

In [14]:
arr[0]

array([34, 45, 56, 78])

In [16]:
arr

array([[ 34,  45,  56,  78],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21, 300,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [ 36,  37,  38,  39],
       [ 40,  41,  42,  43],
       [ 44,  45,  46,  47],
       [ 48,  49,  50,  51],
       [ 52,  53,  54,  55],
       [ 56,  57,  58,  59]])

In [24]:
arr[-1,-1]='aryan'

ValueError: invalid literal for int() with base 10: 'aryan'

In [42]:
arr[0][::-1]

array([78, 56, 45, 34])

In [41]:
Name="aryan"
Name[::-1]

'nayra'

In [44]:
#to find minimun in array 
np.min(arr)

4

In [46]:
#to find maximum in array
np.max(arr)

300

In [49]:
#to find the sum of array
np.sum(arr)

2255

In [51]:
#to find the average
np.mean(arr)

37.583333333333336

In [53]:
#to sort the array
np.sort(arr)

array([[ 34,  45,  56,  78],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  23, 300],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [ 36,  37,  38,  39],
       [ 40,  41,  42,  43],
       [ 44,  45,  46,  47],
       [ 48,  49,  50,  51],
       [ 52,  53,  54,  55],
       [ 56,  57,  58,  59]])

In [55]:
arr[::-1]

array([[ 56,  57,  58,  59],
       [ 52,  53,  54,  55],
       [ 48,  49,  50,  51],
       [ 44,  45,  46,  47],
       [ 40,  41,  42,  43],
       [ 36,  37,  38,  39],
       [ 32,  33,  34,  35],
       [ 28,  29,  30,  31],
       [ 24,  25,  26,  27],
       [ 20,  21, 300,  23],
       [ 16,  17,  18,  19],
       [ 12,  13,  14,  15],
       [  8,   9,  10,  11],
       [  4,   5,   6,   7],
       [ 34,  45,  56,  78]])

In [57]:
np.sort(arr[::-1])

array([[ 56,  57,  58,  59],
       [ 52,  53,  54,  55],
       [ 48,  49,  50,  51],
       [ 44,  45,  46,  47],
       [ 40,  41,  42,  43],
       [ 36,  37,  38,  39],
       [ 32,  33,  34,  35],
       [ 28,  29,  30,  31],
       [ 24,  25,  26,  27],
       [ 20,  21,  23, 300],
       [ 16,  17,  18,  19],
       [ 12,  13,  14,  15],
       [  8,   9,  10,  11],
       [  4,   5,   6,   7],
       [ 34,  45,  56,  78]])

In [60]:
arr.dtype

dtype('int32')

In [62]:
arr.shape

(15, 4)

In [64]:
arr2=np.array([2,5,9,2])

In [65]:
arr+arr2

array([[ 36,  50,  65,  80],
       [  6,  10,  15,   9],
       [ 10,  14,  19,  13],
       [ 14,  18,  23,  17],
       [ 18,  22,  27,  21],
       [ 22,  26, 309,  25],
       [ 26,  30,  35,  29],
       [ 30,  34,  39,  33],
       [ 34,  38,  43,  37],
       [ 38,  42,  47,  41],
       [ 42,  46,  51,  45],
       [ 46,  50,  55,  49],
       [ 50,  54,  59,  53],
       [ 54,  58,  63,  57],
       [ 58,  62,  67,  61]])